/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kadai002;

public class App {
    public String getGreeting() {
        String str1 = "Hello";
        str2.compareTo(str1);
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
